"""
TLS-spoofing HTTP transport for the TTM worker.

Uses `curl_cffi` to impersonate the TLS/JA3/JA4 fingerprint, HTTP/2 frame order,
and header order of a real browser (Chrome/Edge/Safari). This is critical
against Akamai Bot Manager, Cloudflare bot fight, and PerimeterX because
plain `httpx`/`aiohttp` advertise a Python TLS fingerprint that any modern
WAF flags instantly.

Falls back to `httpx` if `curl_cffi` isn't installed — same API, but TLS
spoofing is lost.

Public surface:
    TLSClient            — low-level async HTTP client
    TLSGraphQLClient     — drop-in replacement for `gql.Client(transport=...)`
    impersonate_target_for(profile)  — map browser profile → curl_cffi target
"""

from __future__ import annotations

import logging
from typing import Any, Dict, Mapping, Optional

log = logging.getLogger("tls_transport")

try:
    from curl_cffi.requests import AsyncSession as _CurlAsyncSession
    HAS_CURL_CFFI = True
except Exception:  # pragma: no cover - environment without curl_cffi
    _CurlAsyncSession = None  # type: ignore[assignment]
    HAS_CURL_CFFI = False


_CHROME_TARGETS = [99, 100, 101, 104, 107, 110, 116, 119, 120, 123, 124, 131]


def impersonate_target_for(browser_profile: Mapping[str, Any]) -> str:
    """Pick a `curl_cffi` impersonate target that best matches the browser
    profile generated by the worker's antidetect fingerprinter.

    Supported curl_cffi targets (as of 0.7.x):
        chrome99..chrome131, edge99..edge101, safari15..safari17_0,
        chrome99_android.

    We round Chrome down to the nearest supported version and fall back to
    chrome131 if the profile lacks a recognised browser.
    """
    browser = (browser_profile.get("browser") or "chrome").lower()
    version = browser_profile.get("browser_version") or ""

    if browser == "chrome":
        try:
            major = int(str(version).split(".")[0])
        except (ValueError, IndexError):
            major = 131
        chosen = max((v for v in _CHROME_TARGETS if v <= major), default=131)
        return f"chrome{chosen}"

    if browser == "edge":
        try:
            major = int(str(version).split(".")[0])
        except (ValueError, IndexError):
            major = 101
        return "edge101" if major >= 100 else "edge99"

    if browser == "safari":
        return "safari17_0"

    if browser == "firefox":
        # No real Firefox impersonation in curl_cffi; chrome131 keeps us
        # at least browser-shaped at the TLS layer
        return "chrome131"

    return "chrome131"


class TLSResponse:
    """Uniform response wrapper so callers don't care which backend ran."""

    __slots__ = ("status_code", "text", "headers", "cookies", "_json_cache")

    def __init__(
        self,
        status_code: int,
        text: str,
        headers: Dict[str, str],
        cookies: Dict[str, str],
        json_cache: Any = None,
    ):
        self.status_code = status_code
        self.text = text
        self.headers = headers
        self.cookies = cookies
        self._json_cache = json_cache

    def json(self) -> Any:
        if self._json_cache is not None:
            return self._json_cache
        import json as _json
        self._json_cache = _json.loads(self.text)
        return self._json_cache


class TLSClient:
    """Async HTTP client with browser-grade TLS/HTTP-2 fingerprint spoofing.

    Usage:
        async with TLSClient(impersonate="chrome131", proxy=p) as cli:
            resp = await cli.get("https://...")
            print(cli.cookies)  # accumulated Set-Cookie state
    """

    def __init__(
        self,
        impersonate: str = "chrome131",
        proxy: Optional[str] = None,
        timeout: float = 30.0,
        default_headers: Optional[Mapping[str, str]] = None,
        cookies: Optional[Mapping[str, str]] = None,
    ):
        self.impersonate = impersonate
        self.proxy = proxy
        self.timeout = timeout
        self.default_headers: Dict[str, str] = dict(default_headers or {})
        self.cookies: Dict[str, str] = dict(cookies or {})
        self._session: Any = None
        self._fallback = False

    async def __aenter__(self) -> "TLSClient":
        await self._ensure_session()
        return self

    async def __aexit__(self, exc_type, exc, tb) -> None:
        await self.close()

    async def _ensure_session(self) -> None:
        if self._session is not None:
            return

        if HAS_CURL_CFFI:
            proxies = None
            if self.proxy:
                proxies = {"http": self.proxy, "https": self.proxy}
            self._session = _CurlAsyncSession(
                impersonate=self.impersonate,
                proxies=proxies,
                timeout=self.timeout,
            )
            self._fallback = False
            return

        # Graceful fallback — no TLS spoofing but the bot still functions
        import httpx
        log.warning(
            "curl_cffi not installed — falling back to httpx (no TLS spoofing). "
            "Install with: pip install curl_cffi"
        )
        self._session = httpx.AsyncClient(
            proxy=self.proxy,
            timeout=self.timeout,
            http2=True,
        )
        self._fallback = True

    async def close(self) -> None:
        if self._session is None:
            return
        try:
            await self._session.close()
        except Exception:
            pass
        self._session = None

    def _merge_headers(self, headers: Optional[Mapping[str, str]]) -> Dict[str, str]:
        merged = dict(self.default_headers)
        if headers:
            merged.update(headers)
        return merged

    def _absorb_cookies(self, resp: Any) -> Dict[str, str]:
        cookies: Dict[str, str] = {}
        try:
            if self._fallback:
                for k, v in resp.cookies.items():
                    cookies[k] = v
            else:
                jar = getattr(resp.cookies, "jar", None) or resp.cookies
                try:
                    for c in jar:
                        cookies[c.name] = c.value
                except TypeError:
                    for k, v in dict(resp.cookies).items():
                        cookies[k] = v
        except Exception:
            pass
        self.cookies.update(cookies)
        return cookies

    async def request(
        self,
        method: str,
        url: str,
        *,
        headers: Optional[Mapping[str, str]] = None,
        json: Any = None,
        data: Any = None,
        params: Any = None,
    ) -> TLSResponse:
        await self._ensure_session()
        merged_headers = self._merge_headers(headers)

        kwargs: Dict[str, Any] = {
            "headers": merged_headers,
            "json": json,
            "data": data,
            "params": params,
        }
        if not self._fallback:
            kwargs["cookies"] = self.cookies

        resp = await self._session.request(method, url, **kwargs)
        new_cookies = self._absorb_cookies(resp)

        return TLSResponse(
            status_code=resp.status_code,
            text=resp.text,
            headers=dict(resp.headers),
            cookies=new_cookies,
        )

    async def get(self, url: str, **kwargs: Any) -> TLSResponse:
        return await self.request("GET", url, **kwargs)

    async def post(self, url: str, **kwargs: Any) -> TLSResponse:
        return await self.request("POST", url, **kwargs)
